python simulate.py ./data_settings/nyt/p_0.5.txt ../models/ml-ope/nyt/beta_final.dat
python simulate.py ./data_settings/nyt/p_0.5.txt ../models/ml-ope/nyt/beta_final.dat
python simulate.py ./data_settings/nyt/p_0.5.txt ../models/ml-ope/nyt/beta_final.dat
python simulate.py ./data_settings/nyt/p_0.5.txt ../models/ml-ope/nyt/beta_final.dat
python simulate.py ./data_settings/nyt/p_0.5.txt ../models/ml-ope/nyt/beta_final.dat
python simulate.py ./data_settings/nyt/p_0.5.txt ../models/ml-ope/nyt/beta_final.dat
python simulate.py ./data_settings/nyt/p_0.5.txt ../models/ml-ope/nyt/beta_final.dat
python simulate.py ./data_settings/nyt/p_0.5.txt ../models/ml-ope/nyt/beta_final.dat
python simulate.py ./data_settings/nyt/p_0.5.txt ../models/ml-ope/nyt/beta_final.dat
python simulate.py ./data_settings/nyt/p_0.5.txt ../models/ml-ope/nyt/beta_final.dat
